
model:
    input_chunk_length: 80
    output_chunk_length: 40
    num_layers: 8
    num_filters: 64
    kernel_size: 3
    dropout: 0.7431
    weight_norm: true
    batch_size: 64
    n_epochs: 200
    lr: 0.001

features:
- TI-19
- TI-3
- FI-19
- FI-11
- TI-1213
- TI-35

TARGETS_clean:
- 2-Amino-2-methylpropanol C4H11NO
- Piperazine C4H10N2
# - Carbon dioxide CO2
# - Ammonia NH3
