wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4655867287936539
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.021368308146925828
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
