wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.15536542179264662
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.009799696073145929
n_epochs:
  value: 200
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
