wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.7996316477317008
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.21409620689988576
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
