wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.13894071036215117
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.007847046273304398
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: true
