wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5011875520486921
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.04332208413203546
n_epochs:
  value: 400
num_filters:
  value: 32
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: true
