wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4735619407601456
input_chunk_length:
  value: 60
kernel_size:
  value: 2
lr:
  value: 0.03262357208732585
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
