wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.8343281573921151
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.28639815511603545
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
