wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.8016941980206059
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.143983148363078
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
