wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.7619960129473313
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.02157098947324663
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: true
