wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.7068683299477755
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.022513830119458084
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
