wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.795937936403301
input_chunk_length:
  value: 40
kernel_size:
  value: 3
lr:
  value: 0.029854916915583687
n_epochs:
  value: 400
num_filters:
  value: 32
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
