wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.8127309619525039
input_chunk_length:
  value: 40
kernel_size:
  value: 4
lr:
  value: 0.025278372403303603
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: true
