wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5761924166562479
input_chunk_length:
  value: 40
kernel_size:
  value: 4
lr:
  value: 0.020279059951822817
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: true
