wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5587743559148375
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.1104712460098196
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
