wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2469832217943169
input_chunk_length:
  value: 80
kernel_size:
  value: 4
lr:
  value: 0.07583687585120939
n_epochs:
  value: 300
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
