# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default.yaml

seed: 1234

project_name: aeml
entity: kjappelbaum
log_model: false
dataframe: /home/kjablonk/documents/aeml/scratch/20220210_smooth_window_16.pkl

tags:

outdir: outputs
