wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.801445328339841
input_chunk_length:
  value: 40
kernel_size:
  value: 5
lr:
  value: 0.020030235121253532
n_epochs:
  value: 300
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
