wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.21010208359141755
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.007187734538668442
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
