wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.807085679879896
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.008084385657885173
n_epochs:
  value: 100
num_filters:
  value: 64
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
