wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6550976335658156
input_chunk_length:
  value: 60
kernel_size:
  value: 3
lr:
  value: 0.006985785264271271
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: true
