wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5871178263395154
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.00727479224664604
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
