wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5788159780810874
input_chunk_length:
  value: 40
kernel_size:
  value: 5
lr:
  value: 0.011050242762439958
n_epochs:
  value: 200
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
