wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.8219904281100879
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.009088674327140778
n_epochs:
  value: 200
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
