wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6704415874560735
input_chunk_length:
  value: 40
kernel_size:
  value: 4
lr:
  value: 0.00903707999551431
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
