wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.6040481416709225
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.008415307946996114
n_epochs:
  value: 200
num_filters:
  value: 8
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
