wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5638904863705961
input_chunk_length:
  value: 40
kernel_size:
  value: 5
lr:
  value: 0.007482316522714401
n_epochs:
  value: 300
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
