wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.442504682678893
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.008322890533576358
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: false
