wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.6429516889374007
input_chunk_length:
  value: 40
kernel_size:
  value: 5
lr:
  value: 0.008487957655422236
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: true
