wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6013288661820508
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.009543437957088174
n_epochs:
  value: 200
num_filters:
  value: 32
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: true
