wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.652190555809597
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.029276403936826397
n_epochs:
  value: 200
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
