wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.6179361954982403
input_chunk_length:
  value: 60
kernel_size:
  value: 4
lr:
  value: 0.009683668857378251
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
