wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7668411863153585
input_chunk_length:
  value: 80
kernel_size:
  value: 5
lr:
  value: 0.007980102289633358
n_epochs:
  value: 300
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
