wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.6214023699542615
input_chunk_length:
  value: 40
kernel_size:
  value: 3
lr:
  value: 0.01764920865952794
n_epochs:
  value: 200
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
