wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.20999197958701005
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.0140758396917963
n_epochs:
  value: 300
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
