wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.639422171749144
input_chunk_length:
  value: 40
kernel_size:
  value: 4
lr:
  value: 0.007699585632903642
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
