wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.48208189415213487
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.20465273906181908
n_epochs:
  value: 100
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
