wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5929805218645396
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.013199158099512567
n_epochs:
  value: 100
num_filters:
  value: 64
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
