wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.7524309319822535
input_chunk_length:
  value: 31
kernel_size:
  value: 5
lr:
  value: 0.015770680930389216
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
