wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.8925315082282463
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.026848836925402225
n_epochs:
  value: 400
num_filters:
  value: 32
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: true
