wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.7867067646792812
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.01651558465194364
n_epochs:
  value: 200
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
