wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.8403361393423706
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.019862550649109457
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
