wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.833528209324708
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.007568055241254139
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
