wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.8104781445638906
input_chunk_length:
  value: 31
kernel_size:
  value: 2
lr:
  value: 0.04059275555409917
n_epochs:
  value: 300
num_filters:
  value: 8
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
