wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6117731549868058
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.03709432258340693
n_epochs:
  value: 300
num_filters:
  value: 16
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
