wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.7379325035223401
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.025131456753570407
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
