wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7435133897185581
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.010539996566781885
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
