wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.6795704733998083
input_chunk_length:
  value: 60
kernel_size:
  value: 4
lr:
  value: 0.02001118662439173
n_epochs:
  value: 400
num_filters:
  value: 32
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
