wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.18060016959338024
input_chunk_length:
  value: 80
kernel_size:
  value: 3
lr:
  value: 0.2079358039876013
n_epochs:
  value: 100
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
