wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.633263420418227
input_chunk_length:
  value: 40
kernel_size:
  value: 2
lr:
  value: 0.06363331799310326
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
