wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.8397311485748271
input_chunk_length:
  value: 40
kernel_size:
  value: 3
lr:
  value: 0.012740196595598248
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
