wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.6313135714418039
input_chunk_length:
  value: 31
kernel_size:
  value: 4
lr:
  value: 0.051455232061295215
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
