wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5313644219924614
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.31550399496796694
n_epochs:
  value: 100
num_filters:
  value: 16
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: false
