wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4722107423262488
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.06531701933835789
n_epochs:
  value: 300
num_filters:
  value: 32
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
