wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3021343415723555
input_chunk_length:
  value: 80
kernel_size:
  value: 5
lr:
  value: 0.020790441507959955
n_epochs:
  value: 400
num_filters:
  value: 32
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
