wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7126274385586392
input_chunk_length:
  value: 40
kernel_size:
  value: 3
lr:
  value: 0.02681884644188954
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: true
