wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.1675668116388766
input_chunk_length:
  value: 31
kernel_size:
  value: 5
lr:
  value: 0.012454754621814673
n_epochs:
  value: 100
num_filters:
  value: 8
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
