wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5380040066988183
input_chunk_length:
  value: 80
kernel_size:
  value: 4
lr:
  value: 0.007311978519785931
n_epochs:
  value: 100
num_filters:
  value: 8
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
