wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4350303134816667
input_chunk_length:
  value: 80
kernel_size:
  value: 3
lr:
  value: 0.09190085886397144
n_epochs:
  value: 100
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
