wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5921198604729855
input_chunk_length:
  value: 31
kernel_size:
  value: 5
lr:
  value: 0.1400032568420722
n_epochs:
  value: 200
num_filters:
  value: 64
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: false
