wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.28868923594810625
input_chunk_length:
  value: 80
kernel_size:
  value: 3
lr:
  value: 0.35708310589899767
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: true
