wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5411130600166887
input_chunk_length:
  value: 60
kernel_size:
  value: 3
lr:
  value: 0.010801856527561536
n_epochs:
  value: 100
num_filters:
  value: 16
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
