wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.246634916239129
input_chunk_length:
  value: 80
kernel_size:
  value: 4
lr:
  value: 0.006779442406261692
n_epochs:
  value: 200
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
