wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.6917773924078505
input_chunk_length:
  value: 80
kernel_size:
  value: 3
lr:
  value: 0.17572507305194887
n_epochs:
  value: 200
num_filters:
  value: 16
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: true
