wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.662392439071118
input_chunk_length:
  value: 60
kernel_size:
  value: 4
lr:
  value: 0.07695125080053526
n_epochs:
  value: 200
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
