wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.8287743625867319
input_chunk_length:
  value: 80
kernel_size:
  value: 2
lr:
  value: 0.007663708130251349
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: true
