wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3983476704088797
input_chunk_length:
  value: 40
kernel_size:
  value: 5
lr:
  value: 0.1953092727178775
n_epochs:
  value: 100
num_filters:
  value: 64
num_layers:
  value: 2
num_outputs:
  value: 0
weight_norm:
  value: true
