wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4186643828342184
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.007583164080780939
n_epochs:
  value: 200
num_filters:
  value: 32
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
