wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.6489768475957802
input_chunk_length:
  value: 80
kernel_size:
  value: 5
lr:
  value: 0.16280439736073274
n_epochs:
  value: 100
num_filters:
  value: 64
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: false
