wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.18957908446773297
input_chunk_length:
  value: 40
kernel_size:
  value: 3
lr:
  value: 0.28295774752573416
n_epochs:
  value: 200
num_filters:
  value: 16
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
