wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3305178202877286
input_chunk_length:
  value: 31
kernel_size:
  value: 3
lr:
  value: 0.0106605078570421
n_epochs:
  value: 200
num_filters:
  value: 32
num_layers:
  value: 4
num_outputs:
  value: 1
weight_norm:
  value: false
