wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7401269454580911
input_chunk_length:
  value: 40
kernel_size:
  value: 5
lr:
  value: 0.022006329730935723
n_epochs:
  value: 200
num_filters:
  value: 64
num_layers:
  value: 2
num_outputs:
  value: 1
weight_norm:
  value: false
