wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3399056775868873
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.046099330395273495
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
