wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.8694368432788808
input_chunk_length:
  value: 80
kernel_size:
  value: 4
lr:
  value: 0.05248349006230538
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 1
weight_norm:
  value: true
