wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.8526036422178361
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.1924200376016272
n_epochs:
  value: 100
num_filters:
  value: 32
num_layers:
  value: 8
num_outputs:
  value: 1
weight_norm:
  value: false
